// <auto-generated />
using System;
using GReSym.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GReSym.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306212918_AddUsername")]
    partial class AddUsername
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GReSym.Core.Entities.Feedback.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("external_id");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<float?>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("rating");

                    b.Property<bool?>("Recommended")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("recommended");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("source")
                        .HasComment("'steam', 'metacritic', 'etc.'");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("reviews_external_id_unique");

                    b.HasIndex("GameId")
                        .HasDatabaseName("reviews_games_FK");

                    b.HasIndex("Rating")
                        .HasDatabaseName("IX_reviews_rating");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_reviews_source");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("GReSym.Core.Entities.GameInfo.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("developer");

                    b.Property<string>("HeaderImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("header_image_url");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("IX_games_release_date");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_games_title");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("GReSym.Core.Entities.GameInfo.GameTag", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("GameId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("game_tags_tags_FK");

                    b.ToTable("game_tags", (string)null);
                });

            modelBuilder.Entity("GReSym.Core.Entities.GameInfo.Screenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("screenshots_games_FK");

                    b.ToTable("screenshots", (string)null);
                });

            modelBuilder.Entity("GReSym.Core.Entities.GameInfo.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("tags_unique");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("GReSym.Core.Entities.SourceData.MetacriticSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CriticReviewsCount")
                        .HasColumnType("int")
                        .HasColumnName("critic_reviews_count");

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<string>("MetacriticUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("metacritic_url");

                    b.Property<float?>("Metascore")
                        .HasColumnType("float")
                        .HasColumnName("metascore");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("int")
                        .HasColumnName("rating_count");

                    b.Property<int?>("UserReviewsCount")
                        .HasColumnType("int")
                        .HasColumnName("user_reviews_count");

                    b.Property<float?>("UserScore")
                        .HasColumnType("float")
                        .HasColumnName("user_score");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("metacritic_source_games_FK");

                    b.HasIndex("MetacriticUrl")
                        .IsUnique()
                        .HasDatabaseName("metacritic_source_unique");

                    b.ToTable("metacritic_source", (string)null);
                });

            modelBuilder.Entity("GReSym.Core.Entities.SourceData.SteamSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<bool?>("IsFree")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_free");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int?>("RecommendationsCount")
                        .HasColumnType("int")
                        .HasColumnName("recommendations_count");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("SteamAppId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("steam_app_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasDatabaseName("steam_source_games_FK");

                    b.HasIndex("SteamAppId")
                        .IsUnique()
                        .HasDatabaseName("steam_source_unique");

                    b.ToTable("steam_source", (string)null);
                });

            modelBuilder.Entity("GReSym.Core.Entities.UserInfo.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_unique");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GReSym.Core.Entities.UserInfo.UserGameRate", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int?>("PlayerHours")
                        .HasColumnType("int")
                        .HasColumnName("player_hours");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<bool?>("Recommend")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("recommend");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId")
                        .HasDatabaseName("users_games_rates_games_FK");

                    b.ToTable("users_games_rates", (string)null);
                });

            modelBuilder.Entity("GReSym.Core.Entities.Feedback.Review", b =>
                {
                    b.HasOne("GReSym.Core.Entities.GameInfo.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GReSym.Core.Entities.GameInfo.GameTag", b =>
                {
                    b.HasOne("GReSym.Core.Entities.GameInfo.Game", "Game")
                        .WithMany("GameTags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GReSym.Core.Entities.GameInfo.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GReSym.Core.Entities.GameInfo.Screenshot", b =>
                {
                    b.HasOne("GReSym.Core.Entities.GameInfo.Game", "Game")
                        .WithMany("Screenshots")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GReSym.Core.Entities.SourceData.MetacriticSource", b =>
                {
                    b.HasOne("GReSym.Core.Entities.GameInfo.Game", "Game")
                        .WithOne("MetacriticSource")
                        .HasForeignKey("GReSym.Core.Entities.SourceData.MetacriticSource", "GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GReSym.Core.Entities.SourceData.SteamSource", b =>
                {
                    b.HasOne("GReSym.Core.Entities.GameInfo.Game", "Game")
                        .WithOne("SteamSource")
                        .HasForeignKey("GReSym.Core.Entities.SourceData.SteamSource", "GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GReSym.Core.Entities.UserInfo.UserGameRate", b =>
                {
                    b.HasOne("GReSym.Core.Entities.GameInfo.Game", "Game")
                        .WithMany("UserGameRates")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GReSym.Core.Entities.UserInfo.User", "User")
                        .WithMany("UserGameRates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GReSym.Core.Entities.GameInfo.Game", b =>
                {
                    b.Navigation("GameTags");

                    b.Navigation("MetacriticSource");

                    b.Navigation("Reviews");

                    b.Navigation("Screenshots");

                    b.Navigation("SteamSource");

                    b.Navigation("UserGameRates");
                });

            modelBuilder.Entity("GReSym.Core.Entities.UserInfo.User", b =>
                {
                    b.Navigation("UserGameRates");
                });
#pragma warning restore 612, 618
        }
    }
}
